### ISSUE TITLE
In active development?

### ISSUE THREAD

**Issue by bonbonio** [peterp/react-native-tags#13]
Hello,

I am using Expo 28 and React 16.3.1 and I get errors about legacy methods being used in <Tag> is there any plan to remove componentWillRecieveProps and issue an updated version?

Would be cool if you could provide a method to auto remove the tag from an array if an x icon is clicked, but I would only look into these if your component will continue to be worked on.

Looks great though, so please let me know!

Regards

**Comment by bonbonio** [comment]
Warnings :) but this component looks truly excellent so might save me writing this feature myself.

I think when they get added, provide an optional property for a delete marker and if its provided (like a font-awesome icon. Then that would assume the role of click to delete, there is also the feature where someone might want a preceding # or something, so maybe a generic prepend property which defaults to empty, and someone could pass an icon or string to it?

**Comment by peterp** [comment]
Thanks! The next version will be targeted towards React 16.3.+ users and those warnings will be removed.

I think having a specific marker might be a bit tough, since the tappable area has to be bigger than 44x44 pixels / points.

I love the idea of adding a prepend string!

**Comment by bonbonio** [comment]
Any ETA on the update? Thanks, not sure if its open-ended or not, as this does work quite nicely.

**Comment by peterp** [comment]
I was on vacation, I'll get this done ASAP, but - please feel free to help out! I love contributions!

**Comment by peterp** [comment]
This was removed in `v1.3.0`
