### ISSUE TITLE
Creating new tag on space click is not good solution. What if i need  space in my tag?

### ISSUE THREAD

**Issue by csingh1** [peterp/react-native-tags#15]

**Comment by peterp** [comment]
@csingh1 Are you interested in implementing this yourself and creating a pull-request?

**Comment by milesscherrer** [comment]
Related to this, would be great if enter also created a tag when there is text in text input. Right now the text just remains in the input.

**Comment by peterp** [comment]
Just a quick update: I've got a pull-request open to solve both of these issues, I'm just testing it before releasing.

**Comment by jkunwar** [comment]
@peterp when will be this new feature released

**Comment by peterp** [comment]
@jkunwar just released :)
