### ISSUE TITLE
calling setState on screen removes tag

### ISSUE THREAD

**Issue by Asfandtnt** [peterp/react-native-tags#16]
i have three input boxes and on button.
my tags get removed if i ever call setState on any textinput or button ... any idea why  ?

**Comment by Asfandtnt** [comment]
i have just notice this issue and i have already send my app to client with this bug :(

**Comment by peterp** [comment]
Hey there, could you let me know which formatting you're talking about?

**Comment by peterp** [comment]
You need to set `initialTags`

`<Tags initialTags={this.state.HashTag} />`

**Comment by Asfandtnt** [comment]
I have no words to thanks you :)
i just woke up and saw your post just tried it in my code and its working like a charm :)
Once again thanks.
