### ISSUE TITLE
deleteTagOnPress not working when readonly set to true

### ISSUE THREAD

**Issue by dongawli** [peterp/react-native-tags#18]
Hi,

Thank you for the tags component, really very simple. 
Is there any way to delete the tags when we set the readonly property true? My requirement is tag without input text. 

Thank you,
- Vijay

**Comment by peterp** [comment]
Hey there, thanks, you might be able to set the `inputStyle ` prop to `height: 0`. I'll expand the readonly property to be discrete about what you're disabling in the future.

```jsx
<Tags inputStyle={{ height: 0 }} />
```

**Comment by dongawli** [comment]
Hi Peter, 

Thank you for quick response.  The solution works but still there is some UI issue. 
The "textInputContainer" style has minWidth: 100 which  still showing the textInput component.  
![image](https://user-images.githubusercontent.com/19324345/44028695-539c3c0a-9f18-11e8-970a-21afbe04a61d.png)

I think, it would be great if textInputContainer style can be made configurable. 

Thank you

**Comment by peterp** [comment]
Hey, thanks for this, I'll try and get this add for you in the next few hours.
