### ISSUE TITLE
How to access tags via this.state

### ISSUE THREAD

**Issue by bonbonio** [peterp/react-native-tags#19]
What is the correct usage of the onChangeTags method, the documentation isn't quite clear as it keeps resetting the tags - is there not an internal array of the component that can be exposed?

**Comment by peterp** [comment]
I'm not sure I understand your problem.

You supply the component an initial set of tags. When tags are updated or removed the `onChangeTags` function is called when tags are added or removed, the first argument is all the tags.

```jsx
<Tags
    initialTags={["dog", "cat", "chicken"]}
    onChangeTags={tags => console.log(tags)}
  />
```

Please let me know if I can make the documentation clearer.

**Comment by bonbonio** [comment]
Yes I saw that, but I want to get a list of the tags the user has entered, for example for sending the list of tags to an API... otherwise the tags are just displayed but have no use... 

Specifically I am asking if their is not a way to get the internal list of managed tags from the component, or if I have to override some functions as described above; as when I tried to override it broke the feature which lists the tags.

**Comment by peterp** [comment]
Hmpf. That is literally what this does. Could you share some of your implementation code?

**Comment by bonbonio** [comment]
<Tags onChangeTags={(tags) => this.setState({ tags: tags })} />

The state only gets set to the most recent tag, and also the tags no longer render before the <Tags> component, I must be doing something silly? Its literally the most basic thing in the world...

  handleSubmit = () => {
    console.log(this.state.tags);
  }

**Comment by peterp** [comment]
Ah, that's because you're re-rendering the component when you call `setState,` have a look at the following:
```jsx
<Tags
  initialTags={this.state.tags}
  onChangeTags={(tags) => this.setState({ tags })}
/>
```

**Comment by peterp** [comment]
I'm going to close this issue. I assume that it's solved now, but feel free to open it if you have another misunderstanding.
