### ISSUE TITLE
Suggestion: Support style classes defined in StyleSheet.create()

### ISSUE THREAD

**Issue by bonbonio** [peterp/react-native-tags#20]
The attribute values for the <Tag> styles only accept a style object, they do not support the adding of styles from StyleSheet.create().

I have to use;

`tagTextStyle={{ color: '#fff', fontWeight: 'bold',fontSize: 12 }}`

whereas I would prefer to use

`tagTextStyle={styles.tagText}`

I think this is a reversion from an earlier version of react-native-tags, as the styles.tagText would be loaded in as id reference to the style, not the styles object, so this throws warnings in the App.

Many thanks

**Comment by bonbonio** [comment]
You closed this, but the v1.6.0 does not support the above? It supports the object but it doesnt seem to allow any Font formatting properties...

**Comment by peterp** [comment]
Argh, you're right. Fix incoming.

**Comment by bonbonio** [comment]
https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TextPropTypes/index.js 

Might help...

**Comment by peterp** [comment]
Ok, I've published `1.6.1`.

**Comment by bonbonio** [comment]
Confirmed as fixed. Thank you.
