### ISSUE TITLE
How to add placeholder text 

### ISSUE THREAD

**Issue by ElangoPrince** [peterp/react-native-tags#24]
How to add Custom place holder text?

**Comment by peterp** [comment]
Hey there, at the moment it's not possible, but that's a great idea. I can do this fairly quickly, are you interested in contributing to this project?

**Comment by ElangoPrince** [comment]
yeah sure peterp. can you please share , how to  do quickly...

**Comment by peterp** [comment]
Hey @ElangoPrince, I've added this functionality via `textInputProps`, you can now forward any of the textInput props like thing:

```javascript
<Tags
    textInputProps={{
      placeholder: "pew mew pew"
    }}
/>
```
