### ISSUE TITLE
Support focus() event like a TextInput component

### ISSUE THREAD

**Issue by bonbonio** [peterp/react-native-tags#25]
When creating references to allow the next keyboard to tab through TextInputs, the focus() call on the Tag field throws an exception. It would be great if support could be added.

The plugin I (obviously) think is great, it should probably become something part of Expo/React-Native as its far better than the others - so excuse my bug finding.

**Comment by peterp** [comment]
Ah, that's nice to hear. Thanks - and this is a great feature request. I'll add it.

**Comment by peterp** [comment]
Hey @bonbonio, I've just added `textInputProps` which will be forwarded to the `TextInput` component, do you think that'll work for you?

```javascript
<Tags
    textInputProps={{
      placeholder: "Any type of animal"
    }}
  />
```

**Comment by peterp** [comment]
I'm going to close this now :)
