### ISSUE TITLE
Unable to show updated value.

### ISSUE THREAD

**Issue by lovey92** [peterp/react-native-tags#28]
Hi @peterp 

I have integrated this library and it is really great library.

I have only one issue and that is I want to make value in 000 - 000 - 0000 format. I have implement the function for the same as well but don't know how to update the state and which prop is used to display the updated value.

For example :- 

onChangeTags={tags => this.props.formatPhone(tags)}

formatPhone is a function which return number value to 000 - 000 - 0000 format but it should not reflect the same in the input field.

Please help!

Thanks 
Regards

Lovedeep Singh

**Comment by peterp** [comment]
Hey there - thanks for the kind words -

`onChangeTags` receives a list of all the tags after they have been inserted. You want to modify them before they're inserted?

**Comment by peterp** [comment]
Hey there, I'm going to close this, but if you need some help please re-open it.
