### ISSUE TITLE
Adding a X at the end of each tag also i can't add a placeholder

### ISSUE THREAD

**Issue by BKShaikh** [peterp/react-native-tags#31]
- Can you kindly add X at the end of each tag i added after importing your library but it will be great if you can add a default X at the end of each tab it will be great in visualizing
- i added place holder but it's not visible but when i press backspace on empty tag input it show's place holder for a sec and disappears after a millisecond

**Comment by peterp** [comment]
Hey there - this is a great feature and is something that can be handled with renderProps. I'll work on making this happen.

**Comment by arpitjacob** [comment]
this be great feature to have as its more intuitive.

**Comment by Bill-Niz** [comment]
hi, did you made the renderProps ?

**Comment by peterp** [comment]
@Bill-Niz Unfortunately not yet. I'll work on adding that this weekend.

**Comment by lnogueir** [comment]
This feature will help a lot. I am really looking forward to be able to add a placeholder.

**Comment by peterp** [comment]
`2.1.0` added a `renderTags` prop.
