### ISSUE TITLE
tags not saving

### ISSUE THREAD

**Issue by RichyNs** [peterp/react-native-tags#33]
When i press done on the keyboard the tags are deleted ...
and how can I write the tags under the text input without changing the size of the text input?

**Comment by peterp** [comment]
You need to save the tags somewhere else when the `onChange` function is called, I'm assuming your component reloads, for some reason, when you tap done. 

When you redisplay the tag component you need to pass them back in...
```javascript
<Tags 
    initialTags={mySavedTags}
    onChange={(tags) => functionThatSavesTheTags(tags)}
/>
```

As for you second question, it's not currently possible to move the text input above the tags.

**Comment by RichyNs** [comment]
I manipulated the styles and was able to display the input above the tags, and thank you for your quick reply.

**Comment by peterp** [comment]
Great! I'm going to close this because this doesn't seem to be an issue with react native tags, but rather a question.

Feel free to open another ticket if you need some help.
