### ISSUE TITLE
When typing fast you can end up with tags not being trimmed

### ISSUE THREAD

**Issue by mushinz** [peterp/react-native-tags#37]
[Case 1](https://prnt.sc/o6311g)
[Case 2](http://prntscr.com/o632eg)

Tags not being trimmed :/ if we type too fast!

**Comment by peterp** [comment]
Hmmm... Strange! That shouldn't be possible, but clearly it is... Do you think you could try reproduce this on a device?

**Comment by peterp** [comment]
@mushinz do you have any feedback on this?

**Comment by NishidaRyu416** [comment]
@peterp I think I know what @mushinz meant.
When finishing adding tags, if the last one is not made a tag by a comma, space or something preferred, the one ends up not being a tag successfully. 
So I suggest that you should add a prop called `onFinish` with a `boolean` argument to make the very last one a tag automatically.

**Comment by peterp** [comment]
@mushinz @NishidaRyu416 Did you type with the keyboard in the simulator or a keyboard on the device?

**Comment by peterp** [comment]
I'm going to close this for now, please feel free to open this again if it persists.

**Comment by AdarshJais** [comment]
Yes, it does persist,
