### ISSUE TITLE
Screenshots Please

### ISSUE THREAD

**Issue by Noitidart** [peterp/react-native-tags#4]
May you please add screenshots (ideally GIF) of this in action in repo? That's the first thing a lot of RN package searchers do. There are so many packages its not easy to install each one, render it respecting properties, then uninstall it if it doesn't fit.

**Comment by LouisJS** [comment]
Also : 

- a link to https://www.npmjs.com/package/react-native-tags from the GitHub Readme
- From which react/react-native this component is supported

Would be great 🎊

**Comment by gianpaj** [comment]
Here is the screenshot gif:
https://giphy.com/gifs/reactnative-react-native-tags-l49JP6xlhGr18yZFe

![alt text](https://media.giphy.com/media/l49JP6xlhGr18yZFe/giphy.gif "gif demo")

Feel free to add it to the readme file.

**Comment by Noitidart** [comment]
Thanks @gianpaj !
