### ISSUE TITLE
Remove text Input.

### ISSUE THREAD

**Issue by zohaib-ehsan** [peterp/react-native-tags#43]
Hi
thanks for a great library. Can we remove text input? Only show tags generated by some other mechanism.

Thanks

**Comment by peterp** [comment]
You can set it to `readonly`, or specify the number of max tags. I guess I could make this more obvious via the documentation.
https://github.com/peterp/react-native-tags/blob/master/Tags/index.js#L118-L129

If you have some time I would really appreciate a pull-request that added that information.

**Comment by zohaib-ehsan** [comment]
Thanks.
I will make the changes and test them. After that, I will try to update it.
