### ISSUE TITLE
Unable to set placeholder without setting initialText to ""

### ISSUE THREAD

**Issue by astrinxit66** [peterp/react-native-tags#47]
Hello,
Currently it is not possible to have a placeholder without setting the initialText prop to "". It is because you set the textInput value to " " (with a space) by default.

In the same way it is not possible to get the placeholder back after removing all tags.

**Comment by peterp** [comment]
Unfortunately that extra space is needed because of the way that android deals with the backspace key on the keyboard.
It does not fire if it doesn't erase anything. So the space is added automatically in order to determine if it should go back to the previous tag.
