### ISSUE TITLE
Synthetic event warning

### ISSUE THREAD

**Issue by borasumer** [peterp/react-native-tags#49]
you get “Warning: This synthetic event is reused for performance reasons” when you touch and delete the tags. event.persist() solves it. 

Cheers.

**Comment by ysrarff** [comment]
> you get “Warning: This synthetic event is reused for performance reasons” when you touch and delete the tags. event.persist() solves it.
> 
> Cheers.

Hi where exactly did you put this snippet of code? Thanks in advance!

**Comment by peterp** [comment]
Fixed in #55
