### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aryankranthi** [peterp/react-native-tags#7]
![screenshot_1523016627](https://user-images.githubusercontent.com/29574535/38598284-9f0e1fb0-3d10-11e8-93b9-b75f8281f4de.png)

**Comment by hecmonn** [comment]
Having the same issue. Any update on this?

**Comment by peterp** [comment]
@aryankranthi @hecmonn I need to upgrade the react dependencies and refactor some of the code, there's an open pull request that does this. I'll try to get this merged in the next few hours.

**Comment by peterp** [comment]
@aryankranthi @hecmonn I've published `v.1.0.0` which supports react@16 and newer react-native versions. Let me know if this works for you.

**Comment by aryankranthi** [comment]
thank you @peterp....
it's working fine for me..
